#############################################################################
# Generated by PAGE version 5.4
#  in conjunction with Tcl version 8.6
#  Oct 05, 2020 07:44:41 PM IST  platform: Windows NT
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    tk_messageBox -title Error -message  "You must open project files from within PAGE."
    exit}


if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(pr,menufgcolor) #000000
set vTcl(pr,menubgcolor) #d9d9d9
set vTcl(pr,menuanalogcolor) #ececec
set vTcl(pr,treehighlight) firebrick
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Relative
}




proc vTclWindow.top44 {base} {
    global vTcl
    if {$base == ""} {
        set base .top44
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu "$top.m56" -background #9ab3f5 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 1920x1005+-115+67
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1924 1057
    wm minsize $top 140 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm title $top "New Toplevel"
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    vTcl:withBusyCursor {
    label $top.lab48 \
        -activebackground #f9f9f9 -activeforeground black -background #7579e7 \
        -disabledforeground #a3a3a3 \
        -font {-family {Comic Sans MS} -size 24 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground #ffffff -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -text W3AF 
    vTcl:DefineAlias "$top.lab48" "Label1" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab49 \
        -activebackground #f9f9f9 -activeforeground black -anchor w \
        -background #9ab3f5 -disabledforeground #a3a3a3 \
        -font {-family {Comic Sans MS} -size 16 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {Enter the website URL:} 
    vTcl:DefineAlias "$top.lab49" "Label2" vTcl:WidgetProc "Toplevel1" 1
    button $top.but52 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #a3d8f4 -disabledforeground #a3a3a3 \
        -font {-family {Comic Sans MS} -size 12 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {SQL Injection detection} 
    vTcl:DefineAlias "$top.but52" "Button1" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent53 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground blue \
        -selectforeground white -width 914 
    vTcl:DefineAlias "$top.ent53" "Entry1" vTcl:WidgetProc "Toplevel1" 1
    button $top.but54 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #a3d8f4 -disabledforeground #a3a3a3 \
        -font {-family {Comic Sans MS} -size 12 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text { XSS detection} 
    vTcl:DefineAlias "$top.but54" "Button2" vTcl:WidgetProc "Toplevel1" 1
    button $top.but55 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #a3d8f4 -disabledforeground #a3a3a3 \
        -font {-family {Comic Sans MS} -size 12 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Logger 
    vTcl:DefineAlias "$top.but55" "Button3" vTcl:WidgetProc "Toplevel1" 1
    menu $top.m56 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(pr,menubgcolor) -font TkMenuFont \
        -foreground $vTcl(pr,menufgcolor) -tearoff 0 
    vTcl::widgets::ttk::scrolledtext::CreateCmd $top.scr62 \
        -borderwidth 2 -relief groove -background $vTcl(actual_gui_bg) \
        -height 342 -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -width 517 
    vTcl:DefineAlias "$top.scr62" "Scrolledtext1" vTcl:WidgetProc "Toplevel1" 1

    $top.scr62.01 configure -background white \
        -font TkTextFont \
        -foreground black \
        -height 3 \
        -highlightbackground #d9d9d9 \
        -highlightcolor black \
        -insertbackground black \
        -insertborderwidth 3 \
        -selectbackground blue \
        -selectforeground white \
        -width 10 \
        -wrap none
    vTcl::widgets::ttk::scrolledtext::CreateCmd $top.scr45 \
        -borderwidth 2 -relief groove -background $vTcl(actual_gui_bg) \
        -height 342 -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -width 522 
    vTcl:DefineAlias "$top.scr45" "Scrolledtext2" vTcl:WidgetProc "Toplevel1" 1

    $top.scr45.01 configure -background white \
        -font TkTextFont \
        -foreground black \
        -height 3 \
        -highlightbackground #d9d9d9 \
        -highlightcolor black \
        -insertbackground black \
        -insertborderwidth 3 \
        -selectbackground blue \
        -selectforeground white \
        -width 10 \
        -wrap none
    vTcl::widgets::ttk::scrolledtext::CreateCmd $top.scr46 \
        -borderwidth 2 -relief groove -background $vTcl(actual_gui_bg) \
        -height 342 -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -width 545 
    vTcl:DefineAlias "$top.scr46" "Scrolledtext3" vTcl:WidgetProc "Toplevel1" 1

    $top.scr46.01 configure -background white \
        -font TkTextFont \
        -foreground black \
        -height 3 \
        -highlightbackground #d9d9d9 \
        -highlightcolor black \
        -insertbackground black \
        -insertborderwidth 3 \
        -selectbackground blue \
        -selectforeground white \
        -width 10 \
        -wrap none
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.lab48 \
        -in $top -x 0 -relx -0.031 -y 0 -width 0 -relwidth 1.043 -height 0 \
        -relheight 0.13 -anchor nw -bordermode ignore 
    place $top.lab49 \
        -in $top -x 0 -relx 0.417 -y 0 -rely 0.199 -width 0 -relwidth 0.184 \
        -height 0 -relheight 0.036 -anchor nw -bordermode ignore 
    place $top.but52 \
        -in $top -x 0 -relx 0.109 -y 0 -rely 0.358 -width 242 -relwidth 0 \
        -height 51 -relheight 0 -anchor nw -bordermode ignore 
    place $top.ent53 \
        -in $top -x 0 -relx 0.256 -y 0 -rely 0.269 -width 914 -relwidth 0 \
        -height 32 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but54 \
        -in $top -x 0 -relx 0.438 -y 0 -rely 0.368 -width 244 -relwidth 0 \
        -height 51 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but55 \
        -in $top -x 0 -relx 0.75 -y 0 -rely 0.368 -width 244 -relwidth 0 \
        -height 51 -relheight 0 -anchor nw -bordermode ignore 
    place $top.scr62 \
        -in $top -x 0 -relx 0.042 -y 0 -rely 0.448 -width 0 -relwidth 0.269 \
        -height 0 -relheight 0.34 -anchor nw -bordermode ignore 
    place $top.scr45 \
        -in $top -x 0 -relx 0.37 -y 0 -rely 0.448 -width 0 -relwidth 0.272 \
        -height 0 -relheight 0.34 -anchor nw -bordermode ignore 
    place $top.scr46 \
        -in $top -x 0 -relx 0.677 -y 0 -rely 0.448 -width 0 -relwidth 0.284 \
        -height 0 -relheight 0.34 -anchor nw -bordermode ignore 
    } ;# end vTcl:withBusyCursor 

    vTcl:FireEvent $base <<Ready>>
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top44 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

